package com.jade.marketplace.seller;

import java.time.LocalDateTime;

import com.jade.marketplace.user.User;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

/**
 * Represents a seller profile
 */
@Entity
@Table(name = "seller_profiles")
public class SellerProfile {
    
    /**
     * Primary user ID key generated by MySQL for each seller user
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * A column for name of the user account that owns this seller profile
     * 
     * @OneToOne indicates a one-to-one relationship between SellerProfile and User
     * @FetchType.LAZY indicates that the user information in this SellerProfile will only be loaded when needed
     * @JoinColumn indicates that the user_id column in the seller_profiles table will be used to join the user table
     * @Nullable indicates that the user_id column is not nullable
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;

    /**
     * A column for name of the store
     */
    @Column(nullable = false, unique = true)
    private String storeName;

    /**
     * A column for store description
     */
    @Column(nullable = false, length = 500)
    private String description;

    /**
     * A column to store when the store was created
     */
    @Column(nullable = false)
    private LocalDateTime createdAt;
    
    /**
     * Constructor
     */
    public SellerProfile(User user, String storeName, String description) {
        this.user = user;
        this.storeName = storeName;
        this.description = description;
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Get the user's ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Get the user's account
     */
    public User getUser() {
        return user;
    }

    /**
     * Get the store name
     */
    public String getStoreName() {
        return storeName;
    }
    
    /**
     * Get the store description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Get the timestamp when the store was created
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Set the store name
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }
    
    
    /**
     * Set the store description
     */
    public void setDescription(String description) {
        this.description = description;
    }
    
}
