package com.jade.marketplace.order;

import java.math.BigDecimal;

import com.jade.marketplace.product.Product;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Represents an order item in an order / checkout result
 */
@Entity
@Table(name = "order_items")
public class OrderItem {
    
    /**
     * Order item ID generated by MySQL
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Order that owns this item
     * @ManyToOne = one order can have multiple order items
     * FetchType.LAZY = only fetch order information when asked
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false)
    private Order order;

    /**
     * Product purchased
     * @ManyToOne = one product can have multiple order items (different customers can have order items of the same product)
     * FetchType.LAZY = only fetch product information when asked
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /**
     * A column for quantity of the order item
     */
    @Column(nullable = false)
    private Integer quantity;

    /**
     * A column for unit price of the order item
     */
    @Column(nullable = false)
    private BigDecimal unitPrice;

    /**
     * Constructor
     * Don't need to have Order order as a parameter because when we create Order, we add these items inside order to establish relationship between them
     */
    public OrderItem(Product product, Integer quantity, BigDecimal unitPrice) {
        this.product = product;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
    }

    /**
     * Set order for this order item
     */
    public void setOrder(Order order) {
        this.order = order;
    }

    /**
     * Get order item ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Get order of this order item
     */
    public Order getOrder() {
        return order;
    }

    /**
     * Get product of this order item
     */
    public Product getProduct() {
        return product;
    }

    /**
     * Get quantity of this order item
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * Get unit price of this order item
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * Get total price of this order item
     */
    public BigDecimal getItemSubtotal() {
        return unitPrice.multiply(BigDecimal.valueOf(quantity));
    }

}
