package com.jade.marketplace.order;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import com.jade.marketplace.user.User;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Represents an order / checkout result
 */
@Entity
@Table(name = "orders")
public class Order {
    
    /**
     * Order ID generated by MySQL
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Buyer who makes this order
     * @ManyToOne = one buyer can make multiple orders
     * FetchType.LAZY = only fetch buyer information when asked
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "buyer_id", nullable = false)
    private User buyer;

    /**
     * Items inside this order
     * @OneToMany = an order can have multiple order items
     * mappedBy = this relationship with order item is controlled by "order"
     * CascadeType.ALL = if something happen to order, do the same thing to order items (e.g., save, delete)
     * orphanRemoval = if delete order item from collection, delete it from database as well
     */
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<OrderItem> items = new ArrayList<>();

    /**
     * A column for order status as an enum
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private OrderStatus status;

    /**
     * A column for total price amount of the order
     */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal totalAmount;

    /**
     * A column for timestamp when order is created
     */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    /**
     * Constructor
     */
    public Order(User buyer, BigDecimal totalAmount) {
        this.buyer = buyer;
        this.totalAmount = totalAmount;
        this.status = OrderStatus.PENDING;
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Add an item to this order
     * Keep relationship between items and item in sync
     * 
     * Purpose: add item to order after the order is created
     * This is for backend system to populate an order, not for clients/users to add items into order
     */
    public void addItem(OrderItem item) {
        // add order item into list of items
        items.add(item);

        // set order for this item
        item.setOrder(this);
    }

    /**
     * Get order ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Get order's buyer
     */
    public User getBuyer() {
        return buyer;
    }

    /**
     * Get order's items
     */
    public List<OrderItem> getOrderItems() {
        return items;
    }

    /**
     * Get order status
     */
    public OrderStatus getOrderStatus() {
        return status;
    }

    /**
     * Set order status
     */
    public void setOrderStatus(OrderStatus status) {
        this.status = status;
    }

    /**
     * Get total price amount
     */
    public BigDecimal getAmount() {
        return totalAmount;
    }

    /**
     * Set total price amount
     */
    public void setAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * Get timestamp when the order is made
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

}
