package com.jade.marketplace.category;

import jakarta.persistence.*;

import java.time.LocalDateTime;

/**
 * Represents a product category
 * 
 * @Entity to indicate this class "Category" is a database table
 * @Table name is called "category"
 */
@Entity
@Table(name="category")
public class Category {

    /**
     * Primary user ID key generated by MySQL for each user
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    /**
     * A column for category name that must not be null and must be unique
     */
    @Column(nullable = false, unique = true)
    private String name;

    /**
     * A column for category description that must not be null and must contain at least 500 characters 
     */
    @Column(nullable = false, length = 500)
    private String description;

    /**
     * A column for timestamp when category is created
     * This must not be null
     */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    /**
     * Default constructor
     */
    public Category() {
    }

    /**
     * Constructor
     */
    public Category(String name, String description) {
        // set name, description, and createdAt
        this.name = name;
        this.description = description;
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Get category id
     */
    public Long getId() {
        return id;
    }

    /**
     * Get category name
     */
    public String getName() {
        return name;
    }

    /**
     * Set category name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Get timestamp when the category is created
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Get category description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Set category description
     */
    public void setDescription(String description) {
        this.description = description;
    }
}