spring:
  datasource:
    url: jdbc:h2:mem:marketplace_test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  flyway:
    enabled: false

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: WARN

aws:
  s3:
    region: us-east-1
    bucket-name: test-bucket
    access-key: test-access-key
    secret-key: test-secret-key