spring:
  datasource:
    url: jdbc:h2:mem:marketplace_test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  flyway:
    enabled: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

logging:
  level:
    root: WARN

aws:
  region: us-east-2
  s3:
    bucket: jade-and-plushies-gang-marketplace