package com.jade.marketplace.user;

import jakarta.persistence.*;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

/**
 * UserDetails represents an application user
 * Spring Security can use it during authentication
 * 
 * @Entity to indicate this class "User" is a database table
 * @Table name is called "users"
 * 
 * "users" table where each row is a User
 * id   email
 * 1    jade@gmail.com
 */
@Entity
@Table(name = "users")
public class User implements UserDetails {

    /**
     * A column for ID generated by MySQL
     * Each user must have an ID that MySQL generates and increments IDs for each user automatically
     * Example:
     * id = 1 uniquely identifies a user
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * A column for user email
     * This is also used as the username for Spring Security login
     * Each user must have an email column that is not null and must be unique
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * A column for BCrypt-hashed password
     * Never store plaintext passwords
     * Each user must have a password column that is not null
     */
    @Column(nullable = false)
    private String password;

    /**
     * A column for user's first name
     * Each user must have a first name column that is not null
     */
    @Column(nullable = false)
    private String firstName;

    /**
     * A column for user's last name
     * Each user must have a last name column that is not null
     */
    @Column(nullable = false)
    private String lastName;

    /**
     * A user can have multiple roles
     * Example:
     * - BUYER only
     * - BUYER + SELLER
     * - ADMIN
     * 
     * @ElementCollection indicates a collection of simple values that should be stored in seperate table 
     * @CollectionTable stores this collection in a seperate table called "user_roles"
     * @JoinColumn link "user_roles" back to users using "user_id"
     * @Enumerated makes sure that we match roles with its corresponding Spring Security string, such as ADMIN to ROLE_ADMIN
     * @Column name is set to "role"
     * 
     * "user_roles" table:
     * user_id     role
     * 1           BUYER
     * 1           SELLER
     */
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "user_roles", joinColumns = @JoinColumn(name = "user_id"))
    @Enumerated(EnumType.STRING)
    @Column(name = "role")
    private Set<Role> roles = new HashSet<>();

    /**
     * A column for timestamp of when the user account was created
     */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    // default construction for User
    public User() {
    }

    // custom construction for User
    public User(String email, String password, String firstName, String lastName, Set<Role> roles) {
        this.email = email;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.roles = roles;
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Converts Role enum into list of Spring Security authorities
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return roles.stream()
                .map(role -> (GrantedAuthority) role::getAuthority)
                .toList();
    }

    /**
     * Spring Security uses username as the login identifier
     * In this project, email is the username
     */
    @Override
    public String getUsername() {
        return email;
    }

    /**
     * Account is not expired
     */
    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    /**
     * Account is not locked
     */
    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    /**
     * Credentials are not expired
     */
    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    /**
     * Account is enabled
     */
    @Override
    public boolean isEnabled() {
        return true;
    }

    /**
     * Get account id
     */
    public Long getId() {
        return id;
    }

    /**
     * Set account id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * We keep getEmail() even though getUsername() returns email,
     * because domain code should read naturally
     */
    public String getEmail() {
        return email;
    }

    /**
     * Set email
     */
    public void setEmail(String email) {
        this.email = email;
    }
    
    /**
     * Get password
     */
    @Override
    public String getPassword() {
        return password;
    }

    /**
     * Set password
     */
    public void setPassword(String password) {
        this.password = password;
    }
    
    /**
     * Get user's first name
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Set user's first name
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    /**
     * Get user's last name
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Set user's last name
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    /**
     * Get user roles
     */
    public Set<Role> getRoles() {
        return roles;
    }

    /**
     * Set user roles
     */
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }
    
    /**
     * Get timestamp when account is created
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Set timestamp when account is created
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}