package com.jade.marketplace.product;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import com.jade.marketplace.category.Category;
import com.jade.marketplace.seller.SellerProfile;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

/**
 * A product listed by a seller
 */
@Entity
@Table(name = "products")
public class Product {

    /**
     * Primary key ID for each product generated by MySQL
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Seller that owns this product
     * @ManyToOne = a seller can have multiple products
     * @FetchType.LAZY = only pull seller information when asked
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_id", nullable = false)
    private SellerProfile sellerProfile;

    /**
     * Category that this product belongs to
     * @ManyToOne = a category can have multiple products
     * @FetchType.LAZY = only pull category information when asked
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;

    /**
     * A column for product name
     */
    @Column(nullable = false, unique = true)
    private String name;

    /**
     * A column for product description
     */
    @Column(nullable = false, length = 1000)
    private String description;

    /**
     * A column for product price
     */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal price;

    /**
     * A column for available quantity
     */
    @Column(nullable = false)
    private Integer quantity;

    /**
     * A column to store the timestamp when the product is created
     */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    /**
     * Product images stored in S3
     * ProductImage stores image URL metadata, not the binary image itself
     * @OneToMany = a product can have multiple images
     * mappedBy = to indicate that the ProductImage owns this relationship
     * CascadeType.ALL = to indicate when something happens to product, automatically do the same thing to its product images (e.g., if save/delete product, also save/delete its images)
     * orphanRemoval = if an image is deleted from its collection, delete it from database as well
     * 
     */
    @OneToMany(mappedBy = "product", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<ProductImage> images = new ArrayList<>();

    /**
     * Constructor
     */
    public Product(SellerProfile sellerProfile, String name, String description, Category category, BigDecimal price, Integer quantity) {
        this.sellerProfile = sellerProfile;
        this.name = name;
        this.description = description;
        this.category = category;
        this.price = price;
        this.quantity = quantity;
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Get product's ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Get product's seller profile
     */
    public SellerProfile getSellerProfile() {
        return sellerProfile;
    }

    /**
     * Get product's name
     */
    public String getName() {
        return name;
    }

    /**
     * Get product's description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Get product's category
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Get product's price
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Get  product's quantity
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * Get product's images
     */
    public List<ProductImage> getImages() {
        return images;
    }

    /**
     * Get product's timestamp when it is created
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Set product's name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Set product's category
     */
    public void setCategory(Category category) {
        this.category = category;
    }

    /**
     * Set product's price
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * Set product's quantity
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * Set product's description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Add an image to this product
     */
    public void addImage(ProductImage image) {
        // add image to list of product images
        images.add(image);

        // set product images
        image.setProduct(this);

    }

    /**
     * Remove all existing product images
     */
    public void removeImages() {
        images.clear();
    }

}
