package com.jade.marketplace.product;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Stores images of a product
 * 
 * The actual image files are stored in S3
 * This table only stores image URLs
 */
@Entity
@Table(name = "product_images")
public class ProductImage {

    /**
     * Product image ID generated by MySQL
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long id;

    /**
     * Product that this image belongs to
     * @ManyToOne = a product can have multiple images
     * @FetchType.LAZY = only fetch product information when asked
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    public Product product;

    /**
     * URL of the image
     */
    @Column(nullable = false, unique = true, length = 1000)
    public String url;

    /**
     * Default constructor
     */
    public ProductImage() {
    }

    /**
     * Constructor
     */
    public ProductImage(Product product, String url) {
        this.product = product;
        this.url = url;
    } 

    /**
     * Get image ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Get image url
     */
    public String getUrl() {
        return url;
    }

    /**
     * Get product that this image belongs to
     */
    public Product getProduct() {
        return product;
    }

    /**
     * Set product that this image belongs to
     */
    public void setProduct(Product product) {
        this.product = product;
    }

    /**
     * Set url of this image
     */
    public void setUrl(String url) {
        this.url = url;
    }

    
}
