package com.jade.marketplace.review;

import java.time.LocalDateTime;

import com.jade.marketplace.product.Product;
import com.jade.marketplace.user.User;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Represents a buyer's review
 */
@Entity
@Table(name = "reviews")
public class Review {

    /**
     * Review ID generated by MySQL
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User who writes the review
     * @ManyToOne = one user can own multiple reviews
     * FetchType.LAZY = only fetch user information when asked
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Product that this review is about
     * @ManyToOne = one product can have multiple reviews
     * FetchType.LAZY = only fetch product information when asked
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /**
     * A column for rating from 1 to 5 starts
     */
    @Column(nullable = false)
    private Integer rating;

    /**
     * A column for written comment
     */
    @Column
    private String comment;

    /**
     * A column for timestamp when the review is created
     */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    /**
     * Constructor
     */
    public Review(User user, Product product, Integer rating, String comment) {
        this.user = user;
        this.product = product;
        this.rating = rating;
        this.comment = comment;
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Get review ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Get product that the review belongs to
     */
    public Product getProduct() {
        return product;
    }

    /**
     * Get user who gives the review
     */
    public User getUser() {
        return user;
    }

    /**
     * Get review's rating
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * Get review's comment
     */
    public String getComment() {
        return comment;
    }

    /**
     * Update review
     */
    public void update(String comment, Integer rating) {
        if (comment != null) {
            this.comment = comment;
        }

        if (rating != null) {
            this.rating = rating;
        }
    }

    /**
     * Get timestamp the review is created
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
    
}
