-- Users table stores all users with the following columns
CREATE TABLE users (
    -- user ID generated by MySQL
    -- BIGINT = large integers
    -- AUTO_INCREMENT = auto-generated by MySQL
    -- PRIMARY KEY = a row value is unique (cannot have same ID in different row)
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- non-null unique email address
    -- VARCHAR(255) = string with max variable length = 255
    email VARCHAR(255) NOT NULL UNIQUE,

    -- non-null password
    password VARCHAR(255) NOT NULL,

    -- non-null first name
    first_name VARCHAR(255) NOT NULL,

    -- non-null last name
    last_name VARCHAR(255) NOT NULL,

    -- non-null LocalDateTime created at timestamp
    created_at DATETIME NOT NULL
);

-- User roles table stores all user roles with the following columns
CREATE TABLE user_roles(
    -- non-null user ID
    -- not UNIQUE because 1 user can have different roles so a row entry is for one role
    user_id BIGINT NOT NULL,

    -- non-null user role
    role VARCHAR(255) NOT NULL,

    -- a constraint for foreign key from user_roles to users
    CONSTRAINT foreign_key_user_roles_to_users
        -- FOREIGN KEY = user_roles.user_id = must point to a real user
        -- REFERENCES users(id) = user_roles.user_id -> users.id
        FOREIGN KEY (user_id) REFERENCES users(id)
        -- if a user is deleted from "users", their rows in "user_roles" are deleted too
        ON DELETE CASCADE
);