-- Category table stores all categories with the following columns
CREATE TABLE categories (
    -- category ID generated by MySQL
    -- BIGINT = large integers
    -- AUTO_INCREMENT = auto-generated by MySQL
    -- PRIMARY KEY = a row value is unique (cannot have same ID in different row)
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- non-null unique category name
    -- VARCHAR(255) = string with max variable length = 255
    name VARCHAR(255) NOT NULL UNIQUE,

    -- non-null description
    description VARCHAR(1000) NOT NULL,

    -- non-null LocalDateTime created at timestamp
    created_at DATETIME NOT NULL
);

-- SellerProfile table stores all seller profiles with the following columns
CREATE TABLE seller_profiles (
    -- seller profile ID generated by MySQL
    -- BIGINT = large integers
    -- AUTO_INCREMENT = auto-generated by MySQL
    -- PRIMARY KEY = a row value is unique (cannot have same ID in different row)
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- non-null unique user ID
    user_id BIGINT NOT NULL UNIQUE,

    -- non-null unique store name
    store_name VARCHAR(255) NOT NULL UNIQUE,

    -- non-null description
    description VARCHAR(1000) NOT NULL,

    -- non-null LocalDateTime created at timestamp
    created_at DATETIME NOT NULL,

    -- a constraint for foreign key from seller_profiles to user
    CONSTRAINT foreign_key_seller_profiles_to_user
        -- FOREIGN KEY = seller_profiles.user_id = must point to a real user
        -- REFERENCES users(id) = seller_profiles.user_id -> users.id
        FOREIGN KEY (user_id) REFERENCES users(id)
        -- if a user is deleted from "users", their rows in "seller_profiles" are deleted too
        ON DELETE CASCADE
);

-- Product table stores all products with the following columns
CREATE TABLE products (
    -- product ID generated by MySQL
    -- BIGINT = large integers
    -- AUTO_INCREMENT = auto-generated by MySQL
    -- PRIMARY KEY = a row value is unique (cannot have same ID in different row)
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- non-null seller profile ID
    seller_id BIGINT NOT NULL,

    -- non-null category ID
    category_id BIGINT NOT NULL,

    -- non-null unique product name
    name VARCHAR(255) NOT NULL UNIQUE,

    -- non-null description
    description VARCHAR(1000) NOT NULL,

    -- non-null price with precision = 10, scale = 2
    price DECIMAL(10, 2) NOT NULL,

    -- non-null quantity
    quantity INT NOT NULL CHECK (quantity >= 0),

    -- non-null LocalDateTime created at timestamp
    created_at DATETIME NOT NULL,

    -- a constraint for foreign key from products to seller
    CONSTRAINT foreign_key_products_to_seller
        -- FOREIGN KEY = products.seller_id = must point to a real seller profile
        -- REFERENCES seller_profiles(id) = products.seller_id -> seller_profiles.id
        FOREIGN KEY (seller_id) REFERENCES seller_profiles(id),
    
    -- a constraint for foreign key from products to category
    CONSTRAINT foreign_key_products_to_category
        -- FOREIGN KEY = products.category_id = must point to a real category
        -- REFERENCES categories(id) = products.category_id -> categories.id
        FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- Product images table stores all images with the following columns
CREATE TABLE product_images (
    -- product image ID generated by MySQL
    -- BIGINT = large integers
    -- AUTO_INCREMENT = auto-generated by MySQL
    -- PRIMARY KEY = a row value is unique (cannot have same ID in different row)
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- non-null product ID
    product_id BIGINT NOT NULL,

    -- non-null unique image URL
    url VARCHAR(1000) NOT NULL UNIQUE,

    -- a constraint for foreign key from product_images to product
    CONSTRAINT foreign_key_product_images_to_product
        -- FOREIGN KEY = product_images.product_id = must point to a real product
        -- REFERENCES products(id) = product_images.product_id -> products.id
        FOREIGN KEY (product_id) REFERENCES products(id)
        -- if a product is deleted from "products", their rows in "product_images" are deleted too
        ON DELETE CASCADE

);