-- Order table stores all orders with the following columns
CREATE TABLE orders (
    -- order ID generated by MySQL
    -- BIGINT = large integers
    -- AUTO_INCREMENT = auto-generated by MySQL
    -- PRIMARY KEY = a row value is unique (cannot have same ID in different row)
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- non-null buyer ID
    buyer_id BIGINT NOT NULL,

    -- non-null order status
    status VARCHAR(50) NOT NULL,

    -- non-null order total amount
    total_amount DECIMAL(10, 2) NOT NULL,

    -- non-null LocalDateTime created at timestamp
    created_at DATETIME NOT NULL,

    -- a constraint for foreign key from orders to buyer
    CONSTRAINT foreign_key_orders_to_buyer
        -- FOREIGN KEY = orders.buyer_id = must point to a real buyer/user
        -- REFERENCES users(id) = orders.buyer_id -> users.id
        FOREIGN KEY (buyer_id) REFERENCES users(id)
);

-- Order item table stores all order items with the following columns
CREATE TABLE order_items (
    -- order item ID generated by MySQL
    -- BIGINT = large integers
    -- AUTO_INCREMENT = auto-generated by MySQL
    -- PRIMARY KEY = a row value is unique (cannot have same ID in different row)
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- non-null order ID
    order_id BIGINT NOT NULL,

    -- non-null product ID
    product_id BIGINT NOT NULL,

    -- non-null order item quantity
    quantity INT NOT NULL,

    -- non-null unit price
    unit_price DECIMAL(10, 2) NOT NULL,

    -- a constraint for foreign key from order items to order
    CONSTRAINT foreign_key_order_items_to_order
        -- FOREIGN KEY = order_items.order_id = must point to a real order
        -- REFERENCES = orders(id) = order_items.order_id -> orders.id
        FOREIGN KEY (order_id) REFERENCES orders(id)
        -- if an order is deleted from "orders", their rows in "order_items" are deleted too
        ON DELETE CASCADE,
    
    -- a constraint for foreign key from order items to product
    CONSTRAINT foreign_key_order_items_to_product
        -- FOREIGN KEY = order_items.product_id = must point to a real product
        -- REFERENCES products(id) = order_items.product_id -> products.id
        FOREIGN KEY (product_id) REFERENCES products(id)
);