-- Review table stores all reviews with the following columns
CREATE TABLE reviews (
    -- review ID generated by MySQL
    -- BIGINT = large integers
    -- AUTO_INCREMENT = auto-generated by MySQL
    -- PRIMARY KEY = a row value is unique (cannot have same ID in different row)
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- non-null user ID
    user_id BIGINT NOT NULL,

    -- non-null product ID
    product_id BIGINT NOT NULL,

    -- non-null user rating
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),

    -- user comment
    comment VARCHAR(500),

    -- non-null LocalDateTime created at timestamp
    created_at DATETIME NOT NULL,

    -- a constraint for foreign key from reviews to user
    CONSTRAINT foreign_key_reviews_to_user
        -- FOREIGN KEY = reviews.user_id = must point to a real user
        -- REFERENCES = users(id) = reviews.user_id -> users.id
        FOREIGN KEY (user_id) REFERENCES users(id)
        -- if a user is deleted from "users", their rows in "reviews" are deleted too
        ON DELETE CASCADE,
    
    -- a constraint for foreign key from reviews to product
    CONSTRAINT foreign_key_reviews_to_product
        -- FOREIGN KEY = reviews.product_id = must point to a real product
        -- REFERENCES = products(id) = reviews.product_id -> products.id
        FOREIGN KEY (product_id) REFERENCES products(id)
        -- if a product is deleted from "products", their rows in "reviews" are deleted too
        ON DELETE CASCADE,
    
    -- only one review per product per user
    CONSTRAINT unique_review_product_user
        UNIQUE (product_id, user_id)
);