-- Iventory table stores all inventory with the following columns
CREATE TABLE inventories (
    -- inventory ID generated by MySQL
    -- BIGINT = large integers
    -- AUTO_INCREMENT = auto-generated by MySQL
    -- PRIMARY KEY = a row value is unique (cannot have same ID in different row)
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- non-null product ID
    product_id BIGINT NOT NULL UNIQUE,

    -- non-null available quantity
    available_quantity INT NOT NULL,

    -- non-null reserved quantity
    reserved_quantity INT NOT NULL,

    -- non-null LocalDateTime updated at timestamp
    updated_at DATETIME NOT NULL,

    -- a constraint for foreign key from inventory to product
    CONSTRAINT foreign_key_inventory_to_product
        -- FOREIGN KEY = inventory.product_id = must point to a real product
        -- REFERENCES products(id) = inventory.product_id -> products.id
        FOREIGN KEY (product_id) REFERENCES products(id)
        -- if a product is deleted from "products", their rows in "inventory" are deleted too
        ON DELETE CASCADE
);