-- Cart table stores all carts with the following columns
CREATE TABLE carts (
    -- cart ID generated by MySQL
    -- BIGINT = large integers
    -- AUTO_INCREMENT = auto-generated by MySQL
    -- PRIMARY KEY = a row value is unique (cannot have same ID in different row)
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- non-null unique user ID
    user_id BIGINT NOT NULL UNIQUE,

    -- non-null LocalDateTime updated at timestamp
    updated_at DATETIME NOT NULL,

    -- a constraint for foreign key from carts to users
    CONSTRAINT foreign_key_carts_to_users
        -- FOREIGN KEY = carts.user_id = must point to a real user
        -- REFERENCES users(id) = carts.user_id -> users.id
        FOREIGN KEY (user_id) REFERENCES users(id)
        -- if a user is deleted from "users", their rows in "carts" are deleted too
        ON DELETE CASCADE
);

-- Cart item table stores all cart items with the following columns
CREATE TABLE cart_items (
    -- cart item ID generated by MySQL
    -- BIGINT = large integers
    -- AUTO_INCREMENT = auto-generated by MySQL
    -- PRIMARY KEY = a row value is unique (cannot have same ID in different row)
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- non-null cart ID
    cart_id BIGINT NOT NULL,

    -- non-null product ID
    product_id BIGINT NOT NULL,

    -- non-null quantity
    quantity INT NOT NULL CHECK (quantity > 0),

    -- a constraint for foreign key from cart items to cart
    CONSTRAINT foreign_key_cart_items_to_cart
        -- FOREIGN KEY = cart_items.cart_id = must point to a real cart
        -- REFERENCES carts(id) = cart_items.cart_id -> carts.id
        FOREIGN KEY (cart_id) REFERENCES carts(id)
        -- if a cart is deleted, its cart items must be deleted as well
        ON DELETE CASCADE,
    
    -- a constraint for foreign key from cart items to product
    CONSTRAINT foreign_key_cart_items_to_product
        -- FOREIGN KEY = cart_items.product_id = must point to a real product
        -- REFERENCES products(id) = cart_items.product_id -> products.id
        FOREIGN KEY (product_id) REFERENCES products(id),
    
    -- allow a product to appear only once per cart
    CONSTRAINT unique_cart_product
        UNIQUE(cart_id, product_id)
);