-- Payment table stores all payments with the following columns
CREATE TABLE payments (
    -- payment ID generated by MySQL
    -- BIGINT = large integers
    -- AUTO_INCREMENT = auto-generated by MySQL
    -- PRIMARY KEY = a row value is unique (cannot have same ID in different row)
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- non-null unique order ID
    order_id BIGINT NOT NULL UNIQUE,

    -- non-null total amount with precision = 10, scale = 2
    total_amount DECIMAL(10, 2) NOT NULL,

    -- non-null payment status
    status VARCHAR(50) NOT NULL,

    -- non-null unique transaction ID
    transaction_id VARCHAR(255) NOT NULL UNIQUE,

    -- non-null unique refund transaction ID
    refund_transaction_id VARCHAR(255) UNIQUE,

    -- non-null LocalDateTime created at timestamp
    created_at DATETIME NOT NULL,

    -- LocalDateTime completed at timestamp
    completed_at DATETIME,

    -- LocalDateTime refunded at timestamp
    refunded_at DATETIME,

    -- LocalDateTime failed at timestamp
    failed_at DATETIME,

    -- a constraint for foreign key from payments to order
    CONSTRAINT foreign_key_payments_to_order
        -- FOREIGN KEY = payments.order_id = must point to a real order
        -- REFERENCES orders(id) = payments.order_id -> orders.id
        FOREIGN KEY (order_id) REFERENCES orders(id)

);