-- Notifications table stores all notifications with the following columns
CREATE TABLE notifications (
    -- notification ID generated by MySQL
    -- BIGINT = large integers
    -- AUTO_INCREMENT = auto-generated by MySQL
    -- PRIMARY KEY = a row value is unique (cannot have same ID in different row)
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- non-null user ID
    user_id BIGINT NOT NULL,

    -- non-null notification type
    type VARCHAR(100) NOT NULL,

    -- non-null message
    message VARCHAR(2000) NOT NULL,

    -- non-null read
    read BOOLEAN NOT NULL DEFAULT FALSE,

    -- non-null LocalDateTime created at timestamp
    created_at DATETIME NOT NULL,

    -- a constraint for foreign key from notifications to user
    CONSTRAINT foreign_key_notifications_to_user
        -- FOREIGN KEY = notifications.user_id = must point to a real user
        -- REFERENCES users(id) = notifications.user_id -> users.id
        FOREIGN KEY (user_id) REFERENCES users(id)
        -- if a user is deleted from "users", their rows in "notifications" are deleted too
        ON DELETE CASCADE
);