package com.jade.marketplace.notification;

import java.time.LocalDateTime;

import com.jade.marketplace.user.User;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Represents notification
 */
@Entity
@Table(name = "notifications")
public class Notification {
    
    /**
     * Notification ID generated by MySQL
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User who receives the notification
     * @ManyToOne = a user can have multiple notifications
     * FetchType.LAZY = only fetch user information when asked
     * 
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * A column for type of notification
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private NotificationType type;

    /**
     * A column for notification message
     */
    @Column(nullable = false)
    private String message;

    /**
     * A column to indicate if the user has read this notification
     */
    @Column(nullable = false)
    private boolean read;

    /**
     * A column for timestamp when notification is created
     */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    /**
     * Constructor
     */
    public Notification(User user, NotificationType type, String message) {
        this.user = user;
        this.type = type;
        this.message = message;
        this.createdAt = LocalDateTime.now();
        this.read = false;
    }

    /**
     * Mark the notification as read
     */
    public void markAsRead() {
        this.read = true;
    }

    /**
     * Get notification ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Get user who receives the notification
     */
    public User getUser() {
        return user;
    }

    /**
     * Get notification type
     */
    public NotificationType getType() {
        return type;
    }

    /**
     * Get notification message
     */
    public String getMessage() {
        return message;
    }

    /**
     * Check whether the notification is read
     */
    public boolean isRead() {
        return read;
    }

    /**
     * Get timestamp when notification is created
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

}
