package com.jade.marketplace.cart;

import java.math.BigDecimal;

import com.jade.marketplace.product.Product;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Represents a cart item inside a cart
 * 
 * Note:
 * Product = the product (e.g., soap brand A)
 * Item = the product with number of quantities (e.g., 10 quantities of soap brand A)
 */
@Entity
@Table(name = "cart_items")
public class CartItem {

    /**
     * Primary ID generated by MySQL
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Cart that this item belongs to
     * @ManyToOne = many items can belong to one cart
     * FetchType.LAZY = only pull cart information when asked
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cart_id", nullable = false)
    private Cart cart;

    /**
     * Product added to the cart
     * @ManyToOne = many products can belong to one cart
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /**
     * A column for quantity of this product inside the cart
     */
    @Column(nullable = false)
    private Integer quantity;

    /**
     * Default constructor
     */
    public CartItem() {
    }

    /**
     * Constructor
     */
    public CartItem(Product product, Integer quantity) {
        this.product = product;
        this.quantity = quantity;
    }

    /**
     * Get cart item ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Get cart item product
     */
    public Product getProduct() {
        return product;
    }

    /**
     * Get cart item quantity
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * Get cart
     */
    public Cart getCart() {
        return cart;
    }

    /**
     * Set cart to this item
     */
    public void setCart(Cart cart) {
        this.cart = cart;
    }

    /**
     * Set product
     */
    public void setProduct(Product product) {
        this.product = product;
    }

    /**
     * Set quantity
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * Calculate subtotal for this item
     * Does not need to pass quantity and product parameters because CartItem already knows its own quantity and product
     */
    public BigDecimal getItemSubtotal() {
        return BigDecimal.valueOf(quantity).multiply(product.getPrice());
    }
    
    
}
