package com.jade.marketplace.cart;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import com.jade.marketplace.user.User;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

/**
 * Represents a buyer's shopping cart
 */
@Entity
@Table(name = "carts")
public class Cart {
    
    /**
     * Primary ID generated by MySQL
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User who owns the cart
     * @OneToOne = one user only has one shopping cart
     * FetchType.LAZY = only pull user information when asked
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;

    /**
     * Items inside the cart
     * @OneToMany = a cart can have multiple products
     * mappedBy = indicate that Product owns this relationship
     * CascadeType.ALL = when something happens to cart, automatically do the same thing to its products (e.g., if save a cart, also save its products)
     * orphanRemoval = if a cart is deleted from its collection, delete it from the database as well
     */
    @OneToMany(mappedBy = "cart", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<CartItem> items = new ArrayList<>();

    /**
     * A column for timestamp when the cart is last updated
     */
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Default constructor
     */
    public Cart() {
    }

    /**
     * Constructor
     */
    public Cart(User user) {
        this.user = user;
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Get cart ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Get cart's user
     */
    public User getUser() {
        return user;
    }

    /**
     * Get items inside the cart
     */
    public List<CartItem> getItems() {
        return items;
    }

    /**
     * Get timestamp when cart is last updated
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Add item into cart
     */
    public void addItem(CartItem item) {
        // add item into list of cart items
        items.add(item);

        // set shopping cart for this item
        item.setCart(this);

        // update the last time cart is updated
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Removes an item from cart
     */
    public void removeItem(CartItem item) {
        // remove item from list of cart items
        items.remove(item);

        // set shopping cart for this item which is null
        item.setCart(null);

        // update the last time cart is updated
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Clears all cart items
     */
    public void clearCart() {
        // remove all items from list of cart items
        items.clear();

        // update the last time cart is updated
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Update cart timestamp whenever cart content changes
     */
    public void updated() {
        this.updatedAt = LocalDateTime.now();
    }

}
