package com.jade.marketplace.payment;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import com.jade.marketplace.order.Order;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

/***
 * Represents payment record for an order
 */
@Entity
@Table(name = "payments")
public class Payment {
    
    /**
     * Payment ID generated by MySQL
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Order that this payment belongs to
     * @OneToOne = one order has only one payment
     * @JoinColumn = store the foreign key (order id) in a column called "order_id"
     * unique = every payment has a unique order ID (no 2 payments belong to the same order)
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false, unique = true)
    private Order order;

    /**
     * A column for total amount of this payment
     * precision = can only has 10 digits
     * scale = 2 can only has 2 cent digits
     */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal totalAmount;

    /**
     * A column for current payment status
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PaymentStatus status;

    /**
     * A column for payment provider transaction ID
     * A transaction ID = the identifier returned by payment provider such as Square, Paypal, etc.
     * If a payment goes wrong, we can search with payment provider using transaction ID to find the exact payment
     */
    @Column(unique = true)
    private String transactionId;

    /**
     * A colum for refund transaction id when payment is refunded
     */
    @Column(unique = true)
    private String refundTransactionId;

    /**
     * A column for timestamp when payment is created
     */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    /**
     * A column for timestamp when payment is completed
     */
    @Column(nullable = true)
    private LocalDateTime completedAt;

    /**
     * A column for timestamp when payment is failed
     */
    @Column(nullable = true)
    private LocalDateTime failedAt;

    /**
     * A column for timestamp when payment is refunded
     */
    @Column(nullable = true)
    private LocalDateTime refundedAt;

    /**
     * Constructor for creating payment in PENDING state
     */
    public Payment(Order order, BigDecimal totalAmount) {
        this.order = order;
        this.totalAmount = totalAmount;
        this.status = PaymentStatus.PENDING;
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Mark a payment as COMPLETED 
     */
    public void markCompleted(String transactionId) {
        this.status = PaymentStatus.COMPLETED;
        this.transactionId = transactionId;
        this.completedAt = LocalDateTime.now();
    }

    /**
     * Mark this payment as FAILED
     */
    public void markFailed(String transactionId) {
        this.status = PaymentStatus.FAILED;
        this.transactionId = transactionId;
        this.failedAt = LocalDateTime.now();
    }

    /**
     * Mark this payment as REFUNDED
     */
    public void markRefunded(String transactionId) {
        this.status = PaymentStatus.REFUNDED;
        this.transactionId = transactionId;
        this.refundedAt = LocalDateTime.now();
    }

    /**
     * Get payment ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Get order this payment belongs to
     */
    public Order getOrder() {
        return order;
    }

    /**
     * Get payment total amount
     */
    public BigDecimal getAmount() {
        return totalAmount;
    }

    /**
     * Get payment status
     */
    public PaymentStatus getStatus() {
        return status;
    }

    /**
     * Get payment's transaction ID
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Get payment's refund transaction ID
     */
    public String getRefundTransactionId() {
        return refundTransactionId;
    }

    /**
     * Get timestamp when the payment is created
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Get timestamp when the payment is completed
     */
    public LocalDateTime getCompletedAt() {
        return completedAt;
    }

    /**
     * Get timestamp when the payment is failed
     */
    public LocalDateTime getFailedAt() {
        return failedAt;
    }

    /**
     * Get timestamp when the payment is refunded
     */
    public LocalDateTime getRefundedAt() {
        return refundedAt;
    }

}
